name = "idlerpg-backend"
main = "src/index.ts"
compatibility_date = "2024-03-01"

[[d1_databases]]
binding = "DB"
database_name = "idlerpg_db"
database_id = "02672a10-3e59-47b9-9534-ed33b2da9513"

[[durable_objects.bindings]]
name = "PLAYER_DO"
class_name = "PlayerDO"

[[durable_objects.bindings]]
name = "WORLD_DO"
class_name = "WorldDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PlayerDO", "WorldDO"]
